server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: mybatis/mapper/**/*.xml                 # mapper映射文件
spring:
  application:
    name: microservicecloud-dept                            # 对外暴露的微服务的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3307/cloudDB01              # 数据库url
    username: root
    password: wxhyr7664
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client: # 把客户端注册进eureka服务列表内
    service-url:
      #     eureka集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # instance-id是name为: microservicecloud-dept 服务的一个实例,
    # 一个服务(这里是microservicecloud-dept,由spring.application.name指定)可以有多个实例
    # 我们项目中有三个实例: microservicecloud-dept8001,microservicecloud-dept8002,microservicecloud-dept8003
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true # 访问路径可以显示IP地址

# 开启prefer-ip-address: true后,点击实例名(超链接)打开的页面的信息
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}